import type { Mutant } from "./schemas";

/**
 * Survivor triage.
 *
 * A raw scan can produce hundreds of surviving mutants, and handing all of
 * them to a developer (or to an LLM) produces a report nobody acts on. Three
 * transformations turn that list into a task:
 *
 *   1. Deduplicate — the same mutation applied at 40 different lines is one
 *      testing gap repeated, not 40 distinct problems.
 *   2. Rank — inverting a permission check matters more than flipping a
 *      counter's direction, and the ordering should say so.
 *   3. Cap — a fixable batch, not an exhaustive audit.
 *
 * This lives in @aitg/shared so the CLI's fix-prompt.md and the dashboard's
 * copy-able prompt are generated by the same rules. Two implementations
 * would drift, and a developer comparing them would lose trust in both.
 */

export interface SurvivorGroup {
  mutatorName: string;
  originalCode?: string;
  mutatedCode?: string;
  filePath: string;
  /** Every line in this file where this exact mutation survived. */
  lines: number[];
  occurrences: number;
  severity: Severity;
  /** Why this ranked where it did — shown to the user, not just internal. */
  rationale: string;
}

export type Severity = "critical" | "high" | "medium" | "low";

const SEVERITY_RANK: Record<Severity, number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
};

/**
 * Base severity by mutator class.
 *
 * Branch and equality mutations sit at the top because a surviving one means
 * a decision in the code was inverted and nothing noticed — the failure mode
 * most likely to ship a real defect. Update operators sit at the bottom
 * because they're frequently cosmetic (loop counters, accumulators) and
 * flooding the list with them buries the branch failures.
 */
const MUTATOR_SEVERITY: Record<string, Severity> = {
  EqualityOperator: "high",
  ConditionalExpression: "high",
  BooleanLiteral: "high",
  LogicalOperator: "medium",
  ArithmeticOperator: "medium",
  OptionalChaining: "medium",
  UpdateOperator: "low",
  StringLiteral: "low",
  ArrayDeclaration: "low",
  ObjectLiteral: "low",
  BlockStatement: "medium",
  AssignmentOperator: "medium",
  MethodExpression: "medium",
  Regex: "medium",
  UnaryOperator: "medium",
};

/**
 * Signals that a mutation sits in code where a silent defect is expensive.
 *
 * Matched against the mutated source line only — deliberately not the file
 * path. Matching the path tags every unrelated loop counter inside
 * `billing/` as a monetary risk, which saturates the ranking: when
 * everything is critical, nothing is. Word boundaries matter for the same
 * reason ("rate" should not fire on "generate").
 */
const SENSITIVE_PATTERNS: Array<{ pattern: RegExp; label: string }> = [
  {
    pattern:
      /\b(role|permission|isAdmin|canAccess|authoriz\w*|authenticat\w*|token|session|credential|password|grant|scope)\b/i,
    label: "access control",
  },
  {
    pattern:
      /\b(price|amount|total|rate|discount|tax|charge|refund|balance|cost|fee|subtotal|currency)\b/i,
    label: "a monetary value",
  },
  {
    pattern: /\b(encrypt\w*|decrypt\w*|verify|signature|sanitiz\w*|escape|hash|nonce)\b/i,
    label: "security",
  },
];

function detectSensitivity(code?: string): string | null {
  if (!code) return null;
  for (const { pattern, label } of SENSITIVE_PATTERNS) {
    if (pattern.test(code)) return label;
  }
  return null;
}

function escalate(severity: Severity): Severity {
  if (severity === "low") return "medium";
  if (severity === "medium") return "high";
  return "critical";
}

/** Stable key: the same mutation on the same line of the same file. */
function groupKey(mutant: Mutant): string {
  return [mutant.filePath, mutant.mutatorName, mutant.originalCode ?? "", mutant.mutatedCode ?? ""].join(
    "\u0000",
  );
}

export interface TriageOptions {
  /** Groups returned. Default 10 — a batch a developer will actually finish. */
  limit?: number;
  /** Restrict to one file, for the per-file prompt. */
  filePath?: string;
}

export interface TriageResult {
  groups: SurvivorGroup[];
  /** Distinct gaps found, before the cap. */
  totalGroups: number;
  /** Raw surviving mutants, before dedup. */
  totalSurvivors: number;
  /** Groups omitted by the cap. */
  omittedGroups: number;
}

export function triageSurvivors(
  survivors: Mutant[],
  options: TriageOptions = {},
): TriageResult {
  const limit = options.limit ?? 10;

  const scoped = options.filePath
    ? survivors.filter((m) => m.filePath === options.filePath)
    : survivors;

  const buckets = new Map<string, Mutant[]>();
  for (const mutant of scoped) {
    const key = groupKey(mutant);
    const bucket = buckets.get(key);
    if (bucket) bucket.push(mutant);
    else buckets.set(key, [mutant]);
  }

  const groups: SurvivorGroup[] = [];

  for (const bucket of buckets.values()) {
    const first = bucket[0];
    if (!first) continue;

    const uniqueLines = [...new Set(bucket.map((m) => m.lineNumber))].sort(
      (a, b) => a - b,
    );

    const base = MUTATOR_SEVERITY[first.mutatorName] ?? "medium";
    const sensitivity = detectSensitivity(first.originalCode);

    // At most one escalation. Stacking a second bump for recurrence pushed
    // nearly every group to critical in testing, which made the ranking
    // carry no information. Recurrence is a tiebreaker in the sort instead.
    const severity = sensitivity ? escalate(base) : base;

    let rationale = describeMutator(first.mutatorName);

    if (sensitivity) {
      rationale = `${rationale} The mutated line touches ${sensitivity}, where an undetected change is expensive.`;
    }

    if (uniqueLines.length >= 5) {
      rationale = `${rationale} It recurs ${uniqueLines.length} times in this file, so the gap is systemic — one well-chosen test may close all of them.`;
    }

    groups.push({
      mutatorName: first.mutatorName,
      originalCode: first.originalCode,
      mutatedCode: first.mutatedCode,
      filePath: first.filePath,
      // Deduplicated. Stryker can emit the same mutation twice on one line at
      // different columns, which rendered as "2 places — lines 13, 13" — a
      // detail that makes the whole report look untrustworthy even though the
      // finding is correct. Occurrences still counts distinct lines, not raw
      // mutants, because the user is being told how many places to fix.
      lines: uniqueLines,
      occurrences: uniqueLines.length,
      severity,
      rationale,
    });
  }

  groups.sort((a, b) => {
    const bySeverity = SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity];
    if (bySeverity !== 0) return bySeverity;
    // Within a severity, the more widespread gap first.
    if (b.occurrences !== a.occurrences) return b.occurrences - a.occurrences;
    return a.filePath.localeCompare(b.filePath);
  });

  return {
    groups: groups.slice(0, limit),
    totalGroups: groups.length,
    totalSurvivors: scoped.length,
    omittedGroups: Math.max(0, groups.length - limit),
  };
}

function describeMutator(mutatorName: string): string {
  switch (mutatorName) {
    case "EqualityOperator":
      return "An equality check was inverted and no test noticed, so the comparison itself is unverified.";
    case "ConditionalExpression":
      return "A branch condition was altered and no test noticed, which usually means the boundary case is untested.";
    case "BooleanLiteral":
      return "A boolean was negated and no test noticed, so at least one path through this code is never exercised with the opposite value.";
    case "LogicalOperator":
      return "AND was swapped for OR (or vice versa) undetected, so only one operand is ever being exercised.";
    case "ArithmeticOperator":
      return "An arithmetic operator was changed and the result was never checked, so the computed value is unverified.";
    case "UpdateOperator":
      return "An increment or decrement was reversed undetected, so the resulting count or accumulator is never asserted.";
    default:
      return "This mutation survived, so the behaviour it changes is executed but not verified.";
  }
}

/** Files ranked by how much testing debt they carry, for the per-file view. */
export function survivorsByFile(
  survivors: Mutant[],
): Array<{ filePath: string; count: number; distinctGaps: number }> {
  const byFile = new Map<string, Mutant[]>();
  for (const mutant of survivors) {
    const bucket = byFile.get(mutant.filePath);
    if (bucket) bucket.push(mutant);
    else byFile.set(mutant.filePath, [mutant]);
  }

  return [...byFile.entries()]
    .map(([filePath, mutants]) => ({
      filePath,
      count: mutants.length,
      distinctGaps: new Set(mutants.map(groupKey)).size,
    }))
    .sort((a, b) => b.count - a.count);
}
