import { PrismaClient } from "@prisma/client";

// Singleton pattern: prevents exhausting Postgres connections from Next.js
// hot-reload creating a new PrismaClient on every file change in dev, and
// from serverless/edge invocations spinning up duplicate clients.

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log:
      process.env.NODE_ENV === "development"
        ? ["query", "warn", "error"]
        : ["warn", "error"],
  });

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}

// Re-export everything generated by Prisma (models, enums, input types)
// so consumers only ever import from "@aitg/database".
export * from "@prisma/client";
